require("core.plugins.ibl")
require("core.plugins.telescope")
require("core.plugins.telescope-file-browser")
require("core.plugins.treesitter")
require("core.plugins.harpoon")
require("core.plugins.colorizer")
require("core.plugins.lualine")
require("core.plugins.gitsigns")
