require("core.plugin_config.ibl")
require("core.plugin_config.telescope")
require("core.plugin_config.telescope-file-browser")
require("core.plugin_config.treesitter")
require("core.plugin_config.harpoon")
require("core.plugin_config.colorizer")
require("core.plugin_config.lualine")
require("core.plugin_config.gitsigns")
